### ISSUE TITLE
Wii you implement bayes net ?

### ISSUE THREAD

**Issue by ihsansatriawan** [fracpete/python-weka-wrapper-examples#2]
I have tried this library, but when i want to try classifier bayes net is does not implement right ? maybe it's good to implement

**Comment by fracpete** [comment]
The _python-weka-wrapper_ library does not provide wrappers for all the classifiers, there are mainly generic wrappers (eg `Classifier`, `SingleClassifierEnhancer`) and some non-generic ones (eg `FilteredClassifier`, `MultiSearch`). You instantiate a `Classifier` object by specifiying what Weka classifier class you want to wrap.

Here is an example of training `BayesNet` on the _iris_ dataset and output model and graph in BIF XML format:

``` python
import weka.core.jvm as jvm
import weka.core.converters as conv
from weka.classifiers import Classifier

jvm.start()

# load iris dataset
data = conv.load_any_file("iris.arff")
data.class_is_last()

# instantiate and build classifier
cls = Classifier(
    classname="weka.classifiers.bayes.BayesNet",
    options=["-Q", "weka.classifiers.bayes.net.search.local.K2", "--", "-P", "2"])
cls.build_classifier(data)
print("\nModel\n")
print(cls)
print("\nBIF graph\n")
print(cls.graph)

jvm.stop()
```

**Comment by ihsansatriawan** [comment]
thx @fracpete your explain, but i need to export Conditional Probability Table from bayesnet into database

**Comment by fracpete** [comment]
You have two choices: either parse the [BIF](http://www.cs.cmu.edu/~fgcozman/Research/InterchangeFormat/) XML that gets output using the `graph` method or have to look at the Java code of BayesNet of how to extract the tables.
_python-weka-wrapper_ gives you native access to the underlying Java methods with the `jwrapper` property. Example `wekaexamples/classifiers/classifiers.py` extracts the rulesets from JRip that way.

**Comment by ihsansatriawan** [comment]
ok thx @fracpete i will try :)

**Comment by ihsansatriawan** [comment]
Hi @fracpete i have success install python-weka-wrapper...and running at REPL python...but when i tried in `file.py` it's always `ImportError: No module named core.jvm` i install with :
- `pip install javabridge`
- `pip install python-weka-wrapper`
