### ISSUE TITLE
Can't import modules python-weka-wrapper from file

### ISSUE THREAD

**Issue by ihsansatriawan** [fracpete/python-weka-wrapper-examples#3]
Hi @fracpete i have success install python-weka-wrapper...and running at REPL python...but when i tried in `file.py` it's always `ImportError: No module named core.jvm` i install with :
- `sudo pip install javabridge`
- `sudo pip install python-weka-wrapper`

**Comment by fracpete** [comment]
I just installed it on Linux Mint 17.2 64bit and had no issues. What is your environment? OS? 32/64bit? Python version? Java version? What's the output of `print(os.sys.path)`?

**Comment by ihsansatriawan** [comment]
Ubuntu 64bit, python 2.7 openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

```
>>> import os
>>> print(os.sys.path)
['', '/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/pebl-1.0.2-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/pyparsing-2.1.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/pydot-1.0.2-py2.7.egg', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/user/.local/lib/python2.7/site-packages', '/home/user/.local/lib/python2.7/site-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
```

**Comment by fracpete** [comment]
What version of Ubuntu are you running? Can you execute the script when you rename it to `blah.py`? Can you post the content of your script?

**Comment by ihsansatriawan** [comment]
Ubuntu 15.04

nope. but when i tried at another dir, it's work.... i don't understand why this happend

**Comment by fracpete** [comment]
Just to clarify: it is now working for you?
Did you have a directory named `weka` or a Python module `weka.py` in the same directory?

**Comment by fracpete** [comment]
No more feedback, hence considered solved.
