### ISSUE TITLE
Is your python weka wrapper examples compatible with python 2.7 ?

### ISSUE THREAD

**Issue by maxihidara** [fracpete/python-weka-wrapper-examples#5]
Hello, sorry to bother you, i am a beginner to python language, and weka.  Is your python weka wrapper examples compatible with python 2.7 ? Thank you.

**Comment by fracpete** [comment]
Yes :-) It says on the project homepage of the underlying library:
https://github.com/fracpete/python-weka-wrapper
Please keep in mind, Python 2.7 will reach its end of life in 2020 (https://pythonclock.org/). I recommend switching to the Python 3 version of the library (https://github.com/fracpete/python-weka-wrapper3 and the corresponding examples https://github.com/fracpete/python-weka-wrapper3-examples/).

**Comment by maxihidara** [comment]
Okay, thank you. I will take a look, and try the example.

    Pada Selasa, 6 November 2018 02.43.32 GMT+7, Peter Reutemann <notifications@github.com> menulis:  
 
 
Yes :-) It says on the project homepage of the underlying library:
https://github.com/fracpete/python-weka-wrapper
Please keep in mind, Python 2.7 will reach its end of life in 2020 (https://pythonclock.org/). I recommend switching to the Python 3 version of the library (https://github.com/fracpete/python-weka-wrapper3 and the corresponding examples https://github.com/fracpete/python-weka-wrapper3-examples/).
