### ISSUE TITLE
name 'args' is not defined

### ISSUE THREAD

**Issue by maxihidara** [fracpete/python-weka-wrapper-examples#6]
Hello, sorry again, i want to ask, why i am getting "name 'args' is not defined" error when i try to run:
# load a dataset
helper.print_info("Loading train: " + args[1])
loader = Loader(classname="weka.core.converters.ArffLoader")
train = loader.load_file(args[1])
train.class_index = train.num_attributes - 1
helper.print_info("Loading test: " + args[2])
test = loader.load_file(args[2])
test.class_is_last()

from your "output_class_distribution" example.
Btw i am trying to build prediction using weka classifier. Thank you. Sorry if my question's so basic.

**Comment by fracpete** [comment]
Please use the mailing list for posting questions:
https://groups.google.com/forum/#!forum/python-weka-wrapper

**Comment by fracpete** [comment]
When executing the module from the command-line, you have to provide two parameters: train and test set.
When calling the module's `main` method, you need to provide a list with three elements: 1st is ignored (contains module file name when called from command-line), train and test.
